// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd-9E_Gl7-znTk35bQkhXOqEnz8GVnSLg',
    appId: '1:180578131691:web:a64ca38cf8d0019cbc68ae',
    messagingSenderId: '180578131691',
    projectId: 'evokfb',
    authDomain: 'evokfb.firebaseapp.com',
    databaseURL: 'https://evokfb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'evokfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfX9G14P1S_9-QPs80QuehBDmJADj9EdI',
    appId: '1:180578131691:android:f70ccedb24aa8939bc68ae',
    messagingSenderId: '180578131691',
    projectId: 'evokfb',
    databaseURL: 'https://evokfb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'evokfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCawyQtUNXMG4A0cGQ4KJY77ZnR07BS7c',
    appId: '1:180578131691:ios:d638db711e234fc6bc68ae',
    messagingSenderId: '180578131691',
    projectId: 'evokfb',
    databaseURL: 'https://evokfb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'evokfb.firebasestorage.app',
    iosBundleId: 'com.example.evokApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCawyQtUNXMG4A0cGQ4KJY77ZnR07BS7c',
    appId: '1:180578131691:ios:d638db711e234fc6bc68ae',
    messagingSenderId: '180578131691',
    projectId: 'evokfb',
    databaseURL: 'https://evokfb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'evokfb.firebasestorage.app',
    iosBundleId: 'com.example.evokApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd-9E_Gl7-znTk35bQkhXOqEnz8GVnSLg',
    appId: '1:180578131691:web:b5779637b4428e60bc68ae',
    messagingSenderId: '180578131691',
    projectId: 'evokfb',
    authDomain: 'evokfb.firebaseapp.com',
    databaseURL: 'https://evokfb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'evokfb.firebasestorage.app',
  );
}
